# Generated by Django 2.0.8 on 2018-08-27 21:52

from django.db import migrations, models
import django.utils.timezone
import expense.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expense_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[(expense.models.Category('Food'), 'Food'), (expense.models.Category('Eating Out'), 'Eating Out'), (expense.models.Category('Monthly Bills'), 'Monthly Bills'), (expense.models.Category('Yearly'), 'Yearly'), (expense.models.Category('Extra'), 'Extra'), (expense.models.Category('Transportation'), 'Transportation'), (expense.models.Category('Out'), 'Out')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='text',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[(expense.models.Category('Food'), 'Food'), (expense.models.Category('Eating Out'), 'Eating Out'), (expense.models.Category('Monthly Bills'), 'Monthly Bills'), (expense.models.Category('Yearly'), 'Yearly'), (expense.models.Category('Extra'), 'Extra'), (expense.models.Category('Transportation'), 'Transportation'), (expense.models.Category('Out'), 'Out')], default=expense.models.Category('Out'), max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='explanation',
            field=models.CharField(default='hello', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
