# Generated by Django 2.0.8 on 2018-08-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20180828_0054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
