# Generated by Django 2.0.8 on 2018-08-27 21:58

from django.db import migrations, models
import django.utils.timezone
import expense.models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_delete_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[(expense.models.Category('Food'), 'Food'), (expense.models.Category('Eating Out'), 'Eating Out'), (expense.models.Category('Monthly Bills'), 'Monthly Bills'), (expense.models.Category('Yearly'), 'Yearly'), (expense.models.Category('Extra'), 'Extra'), (expense.models.Category('Transportation'), 'Transportation'), (expense.models.Category('Out'), 'Out')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
