# Generated by Django 2.0.8 on 2018-08-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', 'FOOD'), ('Eating Out', 'EATING_OUT'), ('Monthly Bills', 'MONTHLY_BILLS'), ('Yearly', 'YEARLY'), ('Transportation', 'TRANSPORTATION'), ('Extra', 'EXTRA'), ('Out', 'OUT')], max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'FOOD'), ('Eating Out', 'EATING_OUT'), ('Monthly Bills', 'MONTHLY_BILLS'), ('Yearly', 'YEARLY'), ('Transportation', 'TRANSPORTATION'), ('Extra', 'EXTRA'), ('Out', 'OUT')], max_length=200),
        ),
    ]
